services:
  db:
    image: "postgres:16"
    ports:
      - "5432:5432"
    env_file: db.env
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", ]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: "flyway/flyway:10.13"
    command: migrate
    env_file: db.env
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

volumes:
  migrations:

